# Generated by Django 4.1.5 on 2023-02-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='identifier',
            field=models.CharField(default='x', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
