# Generated by Django 4.1.5 on 2023-02-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tracking',
            unique_together={('user', 'app')},
        ),
    ]
