# Generated by Django 4.1.5 on 2023-02-20 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_scraper', '0002_alter_tracking_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='shopify_scraper.app', unique=True),
        ),
    ]
