# Generated by Django 4.1.5 on 2023-02-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_scraper', '0006_alter_app_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='image',
            new_name='image_file',
        ),
        migrations.AddField(
            model_name='app',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
